/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.quiz.gui;
import com.quiz.logic.User;
import javax.swing.JOptionPane;

/**
 *
 * @author ibrah
 */
public class LoginFrame extends javax.swing.JFrame {
    private String role;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame(String role) {
        initComponents();
        this.role = role;
        
        // Dynamically update your UI based on the role passed
        if (role.equals("Teacher")) {
            lbl_Id.setText("Admin ID:");
            lbl_Title.setText("Teacher Portal Login");
        } else {
            lbl_Id.setText("Roll No:");
            lbl_Title.setText("Student Portal Login");
        }   
        this.setLocationRelativeTo(null);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Login = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        lbl_UserName = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        lbl_Id = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        chk_ShowPassword = new javax.swing.JCheckBox();
        btn_Back = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_Login = new javax.swing.JButton();
        txt_UserName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Login.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Title.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Login");

        lbl_UserName.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_UserName.setText("User Name ");
        lbl_UserName.setAutoscrolls(true);

        txt_Id.addActionListener(this::txt_IdActionPerformed);

        lbl_Id.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_Id.setText("ID");
        lbl_Id.setAutoscrolls(true);

        lbl_Password.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        lbl_Password.setText("Password");
        lbl_Password.setAutoscrolls(true);

        txt_Password.addActionListener(this::txt_PasswordActionPerformed);

        chk_ShowPassword.setText("Show Password");
        chk_ShowPassword.addActionListener(this::chk_ShowPasswordActionPerformed);

        btn_Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Back.addActionListener(this::btn_BackActionPerformed);

        btn_Login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Login.setText("Login");
        btn_Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Login.addActionListener(this::btn_LoginActionPerformed);

        txt_UserName.addActionListener(this::txt_UserNameActionPerformed);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz MasterPro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_LoginLayout = new javax.swing.GroupLayout(pnl_Login);
        pnl_Login.setLayout(pnl_LoginLayout);
        pnl_LoginLayout.setHorizontalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_ShowPassword)
                            .addGroup(pnl_LoginLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                                        .addComponent(lbl_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                        .addGap(155, 155, 155))
                                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                                        .addComponent(lbl_Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(217, 217, 217))
                                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                                        .addComponent(lbl_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(142, 142, 142))))
                            .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        pnl_LoginLayout.setVerticalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chk_ShowPassword)
                .addGap(18, 18, 18)
                .addComponent(btn_Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Back)
                .addGap(68, 68, 68))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void chk_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_ShowPasswordActionPerformed
        if (chk_ShowPassword.isSelected()) {
            txt_Password.setEchoChar((char) 0);        // TODO add your handling code here:
    }//GEN-LAST:event_chk_ShowPasswordActionPerformed
    else {
            txt_Password.setEchoChar('*');
        }
    }
    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
    String id = txt_Id.getText().trim();
    String username = txt_UserName.getText().trim();
    String pass = new String(txt_Password.getPassword()).trim();

    if (username.isEmpty() || id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (this.role.equals("Teacher")) {
        
        if (id.equals("1006") && pass.equals("hello")) {
            JOptionPane.showMessageDialog(this, "Welcome Back, Professor Saleem!");
            new AdminFrame().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Admin ID or Password!", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
       
        JOptionPane.showMessageDialog(this, "Login Successful! Good luck on your quiz.");
        com.quiz.logic.UserSession session = new com.quiz.logic.UserSession(username, id);
        new QuizFrame(session).setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserNameActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
                                        
    new MainPortalFrame().setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Login;
    private javax.swing.JCheckBox chk_ShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_UserName;
    private javax.swing.JPanel pnl_Login;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
