/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.quiz.gui;
import com.quiz.logic.Question;
import com.quiz.logic.UserSession;
import com.quiz.database.DataBaseHandler;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import com.quiz.logic.UserSession;

/**
 *
 * @author ibrah
 */
public class QuizFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizFrame.class.getName());
    private UserSession session;
    private List<Question> questionsList;
    private Timer quizTimer;
    private int totalTimeLeft = 600;
    /**
     * Creates new form QuizFrame
     */
    public QuizFrame(UserSession session) {
        initComponents();
        this.session = session; // 4. Save the passed session into our variable
        this.setLocationRelativeTo(null); // Centers the frame on your screen
        
        // Fetch questions from Derby
        this.questionsList = DataBaseHandler.getQuestionsFromDB();
        
        if (questionsList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No questions found in the database!");
            new MainPortalFrame().setVisible(true);
            this.dispose();
            return;
        }
        
        // Setup our beautiful 10-minute overall progress bar limits
        jProgressBar1.setMaximum(600);
        jProgressBar1.setValue(600);
        
        displayQuestion();
        startOverallTimer();
    }

    // This runs ONCE at startup and manages the full exam countdown smoothly
    private void startOverallTimer() {
        quizTimer = new Timer(1000, e -> {
            totalTimeLeft--;
            jProgressBar1.setValue(totalTimeLeft);
            
            // Format time left into minutes and seconds for better feedback
            int mins = totalTimeLeft / 60;
            int secs = totalTimeLeft % 60;
            
            // ARCHITECT TIP: If you have a time label, you can update it here.
            // Example: lbl_Timer.setText(String.format("%02d:%02d", mins, secs));

            if (totalTimeLeft <= 0) {
                quizTimer.stop();
                JOptionPane.showMessageDialog(this, "Time is completely up! Auto-submitting your quiz.");
                forceSubmitQuiz();
            }
        });
        quizTimer.start();
    }

    private void displayQuestion() {
        Question current = questionsList.get(session.getCurrentQuestionIndex());
        
        // Dynamically updates the question text slot
        lbl_Question.setText((session.getCurrentQuestionIndex() + 1) + ". " + current.getText());
        
        String[] opts = current.getOptions();
        rdb_OptionA.setText(opts[0]);
        rdb_OptionB.setText(opts[1]);
        rdb_OptionC.setText(opts[2]);
        rdb_OptionD.setText(opts[3]);
        
        // Wipe away previous selections so the new question is blank
        buttonGroup1.clearSelection();
    }

    // FIX 1: This handles extracting and saving the current bubble choice
    private void checkSelectedAnswer() {
        int selectedIdx = -1;
        if (rdb_OptionA.isSelected()) selectedIdx = 0;
        else if (rdb_OptionB.isSelected()) selectedIdx = 1;
        else if (rdb_OptionC.isSelected()) selectedIdx = 2;
        else if (rdb_OptionD.isSelected()) selectedIdx = 3;
        
        Question current = questionsList.get(session.getCurrentQuestionIndex());
        if (current.checkAnswer(selectedIdx)) {
            session.addScore();
        }
    }

    // FIX 2: This steps forward or saves everything when reaching the final card
    private void advanceQuiz() {
        session.nextQuestion();
        
        if (session.getCurrentQuestionIndex() < questionsList.size()) {
            // Keep going to the next question!
            displayQuestion();
        } else {
            
            quizTimer.stop();
            forceSubmitQuiz();
        }
    }

    // Helper method to execute submission and switch back cleanly
    private void forceSubmitQuiz() {
        // Upload the results cleanly straight into 
        DataBaseHandler.saveResultToDB(session.getRollNo(), session.getName(), session.getScore());
        
        JOptionPane.showMessageDialog(this, "Quiz Finished!\n" + session.getFinalResult());
        new MainPortalFrame().setVisible(true);
        this.dispose();
        }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_Question = new javax.swing.JLabel();
        rdb_OptionA = new javax.swing.JRadioButton();
        btn_Next = new javax.swing.JButton();
        rdb_OptionB = new javax.swing.JRadioButton();
        rdb_OptionD = new javax.swing.JRadioButton();
        rdb_OptionC = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        lbl_Question.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        buttonGroup1.add(rdb_OptionA);
        rdb_OptionA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_OptionA.setText("Option A");
        rdb_OptionA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdb_OptionA.addActionListener(this::rdb_OptionAActionPerformed);

        btn_Next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Next.setText("Next");
        btn_Next.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Next.addActionListener(this::btn_NextActionPerformed);

        buttonGroup1.add(rdb_OptionB);
        rdb_OptionB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_OptionB.setText("Option B");

        buttonGroup1.add(rdb_OptionD);
        rdb_OptionD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_OptionD.setText("Option D");
        rdb_OptionD.addActionListener(this::rdb_OptionDActionPerformed);

        buttonGroup1.add(rdb_OptionC);
        rdb_OptionC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdb_OptionC.setText("Option C");
        rdb_OptionC.addActionListener(this::rdb_OptionCActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quiz MasterPro");

        jProgressBar1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(250, 250, 250)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdb_OptionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(rdb_OptionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb_OptionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdb_OptionD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lbl_Question, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdb_OptionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_OptionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(rdb_OptionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_OptionD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_OptionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_OptionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_OptionCActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        checkSelectedAnswer();
        advanceQuiz();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NextActionPerformed

    private void rdb_OptionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_OptionAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_OptionAActionPerformed

    private void rdb_OptionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_OptionDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_OptionDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
   }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//              java.awt.EventQueue.invokeLater(() -> new QuizFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbl_Question;
    private javax.swing.JRadioButton rdb_OptionA;
    private javax.swing.JRadioButton rdb_OptionB;
    private javax.swing.JRadioButton rdb_OptionC;
    private javax.swing.JRadioButton rdb_OptionD;
    // End of variables declaration//GEN-END:variables
}
